# Generated by Django 4.2 on 2024-12-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
