# Generated by Django 4.2 on 2024-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_options_alter_seller_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='upadated_date',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
