# Generated by Django 4.2 on 2024-12-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_upadated_date_seller_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
